name: Solar Theme
url: http://roachhd.github.io/unix
description: A stylish Solar themed blog for my Uni Extras. 

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
