name: Solar Theme
url: http://roachhd.github.io/solar-theme-jekyll/
description: A stylish blog using the Solarized color palette
baseurl: http://roachhd.github.io/solar-theme-jekyll/

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
