name: UNI Xtras
url: http://roachhd.github.io/unix/
description: A stylish Solarized blog for my Uni Extras.
baseurl: http://roachhd.github.io/unix/

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
